### ISSUE TITLE
Marketing landing page

### ISSUE THREAD

**Issue by bambanah** [bambanah/melvin#67]
We need the login page to not be the first thing you see when logging in. Having a landing page (even if it's super simple) will be a lot more welcoming, even for people who are familiar with the product.

* [Notion Design Doc](https://www.notion.so/bambanah/Marketing-Dashboard-Technical-Design-ff2f0db908144b30a0230ecb13ddfafb)
* [Figma Designs](https://www.figma.com/file/Q2WBMhMUmG9VHpaoWYKqoT/Marketing?type=design&node-id=1-2&mode=design&t=QfqiywsM2y1uWnbC-0)

## Tasks
- [x] Update all dashboard URLs to `/dashboard/*`
- [x] Implement skeleton marketing page
- [ ] Implement Hero section for landing page

**Comment by bambanah** [comment]
Research outcomes:
* Dashboard URL: https://melvin.care/dashboard/
* Already signed in users will be redirected from melvin.care -> melvin.care/dashboard/
